// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9KgTN-DmeBvyI4Sxtdtpgu1dT6CD3JSE',
    appId: '1:101692845531:web:ba6f57ed36e2f864a28bfe',
    messagingSenderId: '101692845531',
    projectId: 'cmsc23proj',
    authDomain: 'cmsc23proj.firebaseapp.com',
    storageBucket: 'cmsc23proj.appspot.com',
    measurementId: 'G-G6XX6XL46E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOc0aZoRGaV78AgFyMklFWn3WoWl5YEd8',
    appId: '1:101692845531:android:b2601f831b0dd204a28bfe',
    messagingSenderId: '101692845531',
    projectId: 'cmsc23proj',
    storageBucket: 'cmsc23proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3OM6ibe3gydqtjHpq_7I8_cDk1OyWTiE',
    appId: '1:101692845531:ios:e1e6f73706baade8a28bfe',
    messagingSenderId: '101692845531',
    projectId: 'cmsc23proj',
    storageBucket: 'cmsc23proj.appspot.com',
    iosClientId: '101692845531-eh3pe7j4180t0ptt4808bsgorgv21pen.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3OM6ibe3gydqtjHpq_7I8_cDk1OyWTiE',
    appId: '1:101692845531:ios:e1e6f73706baade8a28bfe',
    messagingSenderId: '101692845531',
    projectId: 'cmsc23proj',
    storageBucket: 'cmsc23proj.appspot.com',
    iosClientId: '101692845531-eh3pe7j4180t0ptt4808bsgorgv21pen.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
